### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/data-table#1]
@muxlowc
I got everything matched up but its still giving me errors for the 320px and 400px screen sizes and I don't know what else to do.

**Comment by muxlowc** [comment]
@AlexanderTahtadjian  I'll give you the mark for this one on my end - all screenshots passed on my computer!

**Comment by muxlowc** [comment]
@AlexanderTahtadjian please close this issue when you get a chance

**Comment by AlexanderTahtadjian** [comment]
Ok thanks
